## old version of qt for previous team
# QMake version 3.1
#Using Qt version 5.15.2 in /usr/lib/x86_64-linux-gnu
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FlightControl.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import redis

# connect to redis server running on raspberry pi
try:
    redisClient = redis.StrictRedis(host='10.122.12.158', port=6379)
    print(redisClient)
    redisClient.ping()
    print('Connected!')
except Exception as ex:
    print('Error:'), ex
    exit('Failed to connect, terminating.')

# QString class provides a Unicode character string
try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

# this try-except block is for...
try:
    _encoding = QtGui.QApplication.UnicodeUTF8

    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)

except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, dismabig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(413, 311)
        Form.setStyleSheet("QPlainTextEdit {\n"
	"	background-color: white;\n"
	"	border-style: outset;\n"
	"	border-width: 2px;\n"
	"	border-radius: 6px;\n"
	"	border-color: black;\n"
	# "    font: bold 11px;\n"
	#"	min-width: 5em;\n"
	#"    padding: 6px;\n"
	"}\n"
        "QPushButton {\n"
	"	background-color: darkgrey;\n"
	"	border-style: outset;\n"
	"	border-width: 2px;\n"
	"	border-radius: 6px;\n"
	"	border-color: black;\n"
	# "    font: bold 11px;\n"
	"	min-width: 5em;\n"
	#"    padding: 6px;\n"
	"}\n"
	"QPushButton#pushButton_5 {\n"
	"	background-color: white;\n"
	"	border-style: outset;\n"
	"	border-width: 2px;\n"
	"	border-radius: 6px;\n"
	"	border-color: black;\n"
	# "    font: bold 11px;\n"
	"	min-width: 5em;\n"
	#"    padding: 6px;\n"
	"}\n"
	"QPushButton:pressed {\n"
	"	background-color: cyan;\n"
	"	border-style: inset;\n"
	"}\n"
        "QComboBox {\n"
	"	background-color: white;\n"
	"	border-style: outset;\n"
	"	border-width: 2px;\n"
	"	border-radius: 6px;\n"
	"	border-color: black;\n"
	# "    font: bold 11px;\n"
	"	min-width: 5em;\n"
	#"    padding: 6px;\n"
	"}\n"
	"QComboBox:pressed {\n"
	"	background-color: cyan;\n"
	"	border-style: inset;\n"
	"}")	
	
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(160, 160, 89, 25))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(50, 200, 89, 25))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(270, 200, 89, 25))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(160, 240, 89, 25))
        self.pushButton_4.setObjectName("pushButton_4")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(80, 70, 121, 25))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.pushButton_5 = QtWidgets.QPushButton(Form)
        self.pushButton_5.setGeometry(QtCore.QRect(210, 70, 121, 25))
        self.pushButton_5.setObjectName("pushButton_5")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(Form)
        self.plainTextEdit.setGeometry(QtCore.QRect(110, 30, 191, 31))
        self.plainTextEdit.setObjectName("plainTextEdit")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        self.pushButton.clicked.connect(self.up)
        self.pushButton_2.clicked.connect(self.left)
        self.pushButton_3.clicked.connect(self.right)
        self.pushButton_4.clicked.connect(self.down)
        self.pushButton_5.clicked.connect(self.modeSubmit)
        
    def up(self):
        currentVal = 10.0
        newVal = currentVal + 1.0
        redisClient.lset("Coordinates", newVal, 0)
        print("Up-button has been pressed")
        
    def left(self):
        # redisClient.decr("Xcoord")
        print("Left-button has been pressed")

    def right(self):
        # redisClient.incr("Xcoord")
        print("Right-button has been pressed")

    def down(self):
        # redisClient.decr("Ycoord")
        print("Down-buttton has been pressed")

    def modeSubmit(self):
        print("\nFlight mode submitted")
        print("Flight mode: ", self.comboBox.currentText())
        
    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "UP"))
        self.pushButton_2.setText(_translate("Form", "LEFT"))
        self.pushButton_3.setText(_translate("Form", "RIGHT"))
        self.pushButton_4.setText(_translate("Form", "DOWN"))
        self.comboBox.setItemText(0, _translate("Form", "Standard"))
        self.comboBox.setItemText(1, _translate("Form", "Standby"))
        self.comboBox.setItemText(2, _translate("Form", "Low-Power"))
        self.comboBox.setItemText(3, _translate("Form", "Performance"))
        self.pushButton_5.setText(_translate("Form", "Submit"))
        self.plainTextEdit.setPlainText(_translate("Form", "   Flight Mode Selection"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
